In [22]:
import seaborn as sns #this is the plotting library I'll be using 
import pandas as pd #"as pd" means that we can use the abbreviation in commands
import matplotlib.pyplot as plt #we need Matplotlib for setting the labels in the Seaborn graphs
import math
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

df = pd.read_csv('../creditcard_small.csv')
df.head()
df.dropna()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,67374,-0.228866,0.086431,0.791165,-1.451021,1.141154,0.070110,0.442420,-0.128557,0.305720,...,0.162295,0.732803,-0.380588,-1.086826,0.376692,-0.481770,-0.077937,-0.220115,9.06,0
99995,67374,-1.336121,1.671947,0.994155,0.420318,-0.440923,-0.008386,-0.893860,-2.051884,-1.091297,...,-1.135695,0.509302,0.074188,0.266186,-0.117614,-0.515392,-0.049653,0.085873,2.50,0
99996,67374,0.662465,-1.336560,0.791566,0.425701,-1.391976,0.145471,-0.476652,0.203164,1.379204,...,-0.063744,-0.548785,-0.103769,0.136687,-0.078936,0.948579,-0.075607,0.053555,269.83,0
99997,67374,-4.930001,-1.090715,0.298037,1.890524,-1.058087,-0.329315,-1.498278,1.750301,-0.325311,...,0.051768,0.166222,-0.585006,0.219239,0.181934,-0.253197,0.113801,-1.043315,45.00,0
99998,67374,0.982019,-0.161026,0.534280,0.714558,0.108865,1.154723,-0.298831,0.417264,0.368293,...,-0.074225,0.088060,0.158234,-0.580906,0.100103,0.373722,0.047812,0.005941,27.88,0

In [23]:
y = df['Class'] #We need to take out the price as our Y-variable
X = df.loc[:,'V1':'V28'] #this slices the dataframe to include all rows and the columns from "area" to "rooms"

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) #split the data, store it into different variables
X_train.head() #The train data

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V19,V20,V21,V22,V23,V24,V25,V26,V27,V28
92336,0.805625,-1.695688,1.352358,-0.282137,-2.253216,0.017385,-1.217197,0.202760,-0.152576,0.596598,...,-0.816060,-0.005321,-0.004854,0.042170,-0.132694,0.590563,-0.139888,1.096028,-0.039289,0.058267
62015,1.100031,-0.102983,1.111263,1.292381,-0.933713,-0.115089,-0.540140,0.190514,0.607337,0.013770,...,-0.019317,-0.162889,0.151511,0.592482,-0.125180,0.561148,0.570113,-0.244571,0.051015,0.021777
5005,-1.552078,-0.531074,1.974243,1.013701,1.024195,-1.144346,0.002698,0.048984,1.339099,-1.057587,...,-0.626285,0.241350,-0.181249,-0.715027,0.328461,0.268026,-0.015884,-0.726971,0.026191,0.155041
56848,-0.419158,0.949003,1.336161,0.854330,0.442809,0.107296,0.772343,-0.182008,-0.640852,0.437477,...,0.674276,0.015254,0.213674,0.779649,-0.181551,0.038274,-0.493093,-0.334844,-0.222714,-0.062746
99373,0.054913,1.758103,-2.796921,1.320415,1.549875,-0.875941,0.498296,0.236048,-0.683338,-1.040652,...,0.407340,0.008538,-0.125729,-0.211676,0.142032,-1.351474,-0.221678,-0.351459,-0.100930,-0.083579

In [24]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(max_depth=None, random_state=1)
model = model.fit(X, y)

//anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [25]:
from sklearn.metrics import confusion_matrix
y_test_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_test_pred) #creates a "confusion matrix"
cm

array([[29934,     0],
       [    3,    63]])

In [26]:
y_test.value_counts()

0    29934
1       66
Name: Class, dtype: int64

0 is no fraude
1 is fraude

In [27]:
#In order to read it easily , let's make a dataframe out of it, and add labels to it.
conf_matrix = pd.DataFrame(cm, index=['no fraude', 'fraude' ], columns = ['nofraude_p', 'fraude_p']) 
conf_matrix

           nofraude_p  fraude_p
no fraude       29934         0
fraude              3        63

The way to read this is that of the fraude cases, 50 are correctly predicted as 'fraude', 16 are instead predicted as 'no fraude'. The recall and precision for fraude is:


$𝑝𝑟𝑒𝑐𝑖𝑠𝑖𝑜𝑛=\frac{63}{63}=1 $


$𝑟𝑒𝑐𝑎𝑙𝑙=\frac{63}{63+3}=.95 $

# Previous settings: with max_depth on 2
What I can say about if these rates ae acceptable for assessing transaction fraud risk. Precision: how much of the predicted fraud is actually fraud, recall: how much of actual fraud is predicted as fraud. I think the recall is not high enough because this means that 25% of the predicted fraud isn't fraud at all. More acceptable to be worse is the precision, because then innocent people do not get blamed for fraude but people that commit fraude are overseen.

# with max-depth: None
Very acceptable numbers

In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     29934
           1       1.00      0.95      0.98        66

    accuracy                           1.00     30000
   macro avg       1.00      0.98      0.99     30000
weighted avg       1.00      1.00      1.00     30000